### PR TITLE
color the log level

### PR DESCRIPTION
**Pull request by l3ifeng**
Add an option for this feature. Select it to make the log easier to read.

Related to #19

### CODE REVIEW

**Comment by l3ifeng** [comment]
@lemin9538 Request review

**Comment by lemin9538** [comment]
I think not all terminal application can support the color feature.  It will dispay garbled on these terminal.

**Comment by l3ifeng** [comment]
@lemin9538 Most common serial port tools support colorized output. This is no different from the colorized output of some commands (such as `ls`). Moreover, this option is turned off by default.

**Comment by lemin9538** [comment]
It is ok for me if the feature is disabled at default.

**Comment by l3ifeng** [comment]
Then it can be merged as is.

**Comment by lemin9538** [comment]
please add a "default n" in the Kconfig for LOG_LEVEL_COLORFUL

**Comment by l3ifeng** [comment]
I'm done.

**Pull request merged**
