### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by le1feng78**

### CODE REVIEW

**Comment by le1feng78** [comment]
@lemin9538 Do you have any suggestion?

**Comment by lemin9538** [comment]
@le1feng78 what's editor do you use ?

**Comment by le1feng78** [comment]
@lemin9538 I am using `Vim`.

**Comment by lemin9538** [comment]
Vim has no issue to display these code at my side. 
By the way I do not think this is a issue.

**Comment by le1feng78** [comment]
@lemin9538 Please take a closer look. This patch is to correct **spelling errors** rather than code formats. Some underscores are missing, and there is a wrong semicolon. When SMP is turned off, code compilation fails.

**Comment by lemin9538** [comment]
Good. 

Could you please add your comments to the git commit message.

**Comment by le1feng78** [comment]
No problem, I will do it later.

**Comment by l3ifeng** [comment]
@lemin9538 My **old** account (@le1feng78) has been locked. I will create new PRs with this account. You can **delete** #17 (if you can see it), #18 and #19 now.

**Comment by lemin9538** [comment]
ok. 

when update the patch, please follow below rules for your git commit message:

[https://chris.beams.io/posts/git-commit/](https://chris.beams.io/posts/git-commit/)

**Pull request closed without merging**
